name: autoDeploy
on:
   push:
      branches: [main]
jobs:
   build:
      name: Build
      runs-on: ubuntu-latest
      steps:
         - name: SSH Remote Commands
           uses: appleboy/ssh-action@v0.1.4
           with:
              host: ${{ secrets.SERVER_IP }}
              username: ${{ secrets.SERVER_USER }}
              password: ${{ secrets.SERVER_PASS }}
              port: ${{ secrets.SERVER_PORT }}
              script: |
                 cd ~/containers/NodeWeb/node_server
                 ${{ secrets.BUILD_SCRIPT }}
