name: autoDeploy
on: 
  pull_request: 
    branches: [ main ]
  push:
    branches: [ main ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: pulling from remote
      uses: JoelYoung01/node_server@main
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/NodeServer
          ${{ secrets.SERVER_DEPLOY_SCRIPT}}
          pm2 restart 0
