name: CI / CD Workflow
run-name: Deploy to PROD started by ${{ github.actor }}
# This workflow will build and deploy the Docker image to the server

on:
  push:
    branches:
      - main
      
jobs:
  Build:
    uses: joelyoung01/Templates/.github/workflows/BuildDockerImage.yaml@main
    with:
      docker_username: joelyoung01
      image_name: personalsite # No capital letters!
    secrets:
      docker_access_key: ${{ secrets.DOCKER_ACCESS_KEY }}
      
  Deploy:
    uses: joelyoung01/Templates/.github/workflows/DeployDockerImage.yaml@main
    needs: Build
    with:
      docker_user: joelyoung01
      image_name: personalsite
      deployment_user: deploy
      host_port: 3000
      server_hostname: joelyoung.dev
    secrets:
      server_ssh_key: ${{ secrets.SERVER_SSH_KEY }}
      server_ssh_port: ${{ secrets.SERVER_SSH_PORT }}